### PR TITLE
Merge master into ticketsale

### PR DESCRIPTION
**Pull request by Kailiangdong**

### CODE REVIEW

**Comment by saileru** [comment]
@kordianbruck Merging directly into the feature branch does not seem to work for us. We are expected to have two approving review. Are we supposed to create a pull request every time we want to merge master into our feature branch?

**Comment by kordianbruck** [comment]
@saileru you are right. As I've setup branch protection for the feature branch, you cannot directly pull into the branch. If you want, I can reduce the number of reviews to one or completely remove the branch protection, if the team agrees to continue to do reviews for each other. Deal?

**Comment by saileru** [comment]
I think the branch protection should probably stay as it gives some safety. It makes it more difficult to break something on the feature branch accidentially.
Another idea would be to merge master into our feature branches before merging them back to feature/ticketsale from time to time. That way we could combine feature ticket reviews and master merging.

**Comment by kordianbruck** [comment]
@saileru that makes changes from master be part of the usual review. Not too nice to look at. For the time being, lets just do a weekly update from master to feature, after our scrum meeting okay?

**Comment by saileru** [comment]
@kordianbruck Ok, sounds good!

**Pull request merged**
