### PR TITLE
Integrate TU Kino

### PR DESCRIPTION
**Pull request by brdvlps**
I basically used the work of @thomasmauerer (PR #289) here.
The TU Kino section is now accessible by tapping the TU Film card.

### CODE REVIEW

**Comment by kordianbruck** [comment]
* When you click on the Card in the News section you get a JSONException because of a null pointer

**Comment by brdvlps** [comment]
Could you specify that exception? For me everything works fine.

**Comment by pfent** [comment]
It would probably make sense to strip the kino information from the NewsCard into a new KinoCard.
However, this probably exceeds this PR...

**Comment by kordianbruck** [comment]
@pfent well good idea. Most of the data is the same, but we also fetch some additional data on the server from imdb. For the future we could also implement a trailer  or such.

@brdvlps 
```
09-20 10:17:04.412    2581-2581/de.tum.in.tumcampus E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: de.tum.in.tumcampus, PID: 2581
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Intent de.tum.in.tumcampus.cards.Card.getIntent()' on a null object reference
            at de.tum.in.tumcampus.cards.Card$CardViewHolder.onClick(Card.java:340)
            at android.view.View.performClick(View.java:4780)
            at android.view.View$PerformClick.run(View.java:19866)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5257)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```
Happens on the News Screen/Activity/Section screenshot from 2015-09-20 10-16-58

**Comment by pfent** [comment]
Replaced the ListView for the NewsActivity with a RecyclerView and properly connected it to the NewsCards.

This wasn't a problem with this PR though, it was broken in an earlier PR of mine

**Comment by kordianbruck** [comment]
Excellent. Thanks @brdvlps & @pfent !

**Comment by thomasmauerer** [comment]
I just recognized a bug in the TU Kino. The titles in the pager strip are not shown, but the adapter class returns the correct titles. It looks like this is a bug in the new support library:
https://code.google.com/p/android/issues/detail?id=183127

However, the solution is probably to wait for the update:
https://code.google.com/p/android/issues/detail?id=185605

**Comment by kordianbruck** [comment]
Let's make that a separate issue. Thanks @thomasmauerer

**Pull request merged**
