### PR TITLE
OPAC implementation

### LINKED ISSUE #11: Library Books: OPAC implementation
Integration der Bibliothek in die app. Besonders Konto Übersicht und opac Katalog

### PR DESCRIPTION
**Pull request by psukys**
## Issue

Allow user to login to library and get information about:
- Items reserved (books, carrels, etc.)
- Items lent
- Money that student owes to the library.

As well, notification when lent book time period is about to expire.

## Screenshot

TBA, when implemented

## Why this is useful for all students

Students can easily get information about their library account and be informed ℹ️ 

Fixes #11

### CODE REVIEW

**Comment by psukys** [comment]
@kordianbruck I think that for this CI needs a step for pulling git submodules

**Comment by pfent** [comment]
@psukys why not just use [the bintray version](https://bintray.com/opacapp/libs/libopac/)?

I think a:
```gradle
implementation 'net.opacapp:libopac:5.2.5'
```
should do just fine? It is included in the jcenter:
https://jcenter.bintray.com/net/opacapp/libopac/

**Comment by psukys** [comment]
@pfent it is and when included it complains that different joda versions are used. I'm just trying to resolve this through adjusting libopac's gradle file.

**Comment by pfent** [comment]
You can try:
```gradle
configurations.all {
    resolutionStrategy {
        force 'net.danlew:android.joda:2.9.9.1'
    }
}
```

Otherwise I'd open an issue with the library and ask them about the best way to include it with gradle...

**Comment by psukys** [comment]
@pfent well they have a [sample project with gradle](https://github.com/opacapp/libopac-sample-gradle), but apparently it does not integrate as seamlessly

**Comment by kordianbruck** [comment]
@psukys is this still feasible or just not doable within a reasonable time frame?

**Comment by psukys** [comment]
infeasible, can't find a way to integrate into current build configuration

**Comment by kordianbruck** [comment]
Postponed indefinitely.

**Pull request closed without merging**
