### PR TITLE
Add test for database migration and versionize schema

### PR DESCRIPTION
**Pull request by pfent**
A simple unit test which applies the migrations on the pre-room database in-order.

I also wanted to use the [MigrationTestHelper](https://medium.com/google-developers/testing-room-migrations-be93cdb0d975), but Roboelectric just decided to be a PITA and fuck up the asset management, on which the helper relies. 

Now I don't automatically verify the schema, but just test, if the migrations succeed without exceptions :man_shrugging:

### CODE REVIEW

**Comment by pfent** [comment]
@kordianbruck turns out, that all the room tests would had been Instrumentation tests, which can only be run on an emulator. Roboelectric simply can't possibly work with that...

I now simply instantiate our database, which correctly triggers migrations and validations of the current schema. I didn't reproduce #701 with that approach, yet. However that seems to be a matter of inserting the right test data into the database

**Comment by kordianbruck** [comment]
@pfent yea, while trying it out yesterday it seemed waaaay too complicated to get it working for what we want it to do.

The Bug really only occures, if you install an app version after one of the first migrations so lets say version 3 and then execute two migrations on it. Somehow when setting it up, it is not using the migrations, but generating the schema from the models. So I really have no clue how to test this, as we cannot do intermediate migration tests

**Comment by pfent** [comment]
@kordianbruck sure we can. Just extract the schema and set the version in `SQLiteOpenHelper`

**Comment by psukys** [comment]
The unittest failure is quite cryptic, but in general I believe that it might be related to persisting TcaDb, where it has to be closed.
Reference test: https://github.com/TCA-Team/TumCampusApp/blob/master/app/src/test/java/de/tum/in/tumcampusapp/managers/SyncManagerTest.java#L37

**Comment by pfent** [comment]
@psukys thanks for the hint, should be fixed now

**Pull request merged**
