### PR TITLE
Organisation improvement

### PR DESCRIPTION
**Pull request by Shifuddin**
Hi, I have updated OrganisationDetailsActivity and add a new class AlternateRequest

#361

### CODE REVIEW

**Comment by TCA-Team** [comment]
Can one of the admins verify this patch?

**Comment by pfent** [comment]
ok to test

**Comment by pfent** [comment]
retest this please

**Comment by pfent** [comment]
@Shifuddin I looked at your code and it doesn't compile with the current state with the TCA code. I suggest you pull and merge the current master branch and fix the compilation warnings.

The changes, that broke your code, were, that I clearyfied the interfaces of the NetUtils to return Optional<String> instead of plain Strings, which need explicit checking, if they really are present.

I would also suggest you:
- [ ] Do not implement a broken caching mechanism on your own, but use the appropriate method in ```NetUtils.downloadStringAndCache```
- [ ] Adhere to the basic code structure in our project: separate classes for models/data and actually doing the requests. 
- [ ] Use separate functions to structure your code. 5 consecutive lines of ```organisation.getFoo().length() == 0```… really?
- [ ] Redo this little piece:
```java
alternateRequest.fetchInteractive("pOrgNr", orgId);
try {
	/*
	 * Wait 1 second for data to be fetched
	 */
	Thread.sleep(1000);
} catch (InterruptedException e) {
	e.printStackTrace();
}
```

**Comment by Shifuddin** [comment]
Hi @pfent ,
I have tried to follow your suggestions. But the problem is I can't build new TCA source code. After build command after 15-20 minute it shows "Error:Execution failed for task ':app:compileV10DebugJavaWithJack'.
> java.lang.RuntimeException: java.lang.OutOfMemoryError: GC overhead limit exceeded".

I thought it's my sdk or studio problem. Then reinstalled everything last night. Then faced same problem. Then I used another machine to see whether my machine is troubling. But same result. It took many hours.

Since I can't see the output, I didn't make too many changes. I just change AlternateRequest java file to remove compilation error. Then did some minor changes in OrgDetailsActivity.

Actually I made major changes on the basis of your suggestions, but got afraid of whether it produce correct result or not since I can't build in my machine. That's why I remove major changes. 

If you can build the project, I will request you provide me the apk so that I can submit it to moodle.
Thanks in advance.

**Comment by pfent** [comment]
did you merge the current master? I enabled a different build system for a few hours but it didn't work out... It seems that you currently are behind the current TCA master branch. Make sure you have commit c0c74fc5a9ecc03386e187f45aecdd6dafae9498 on your local branch. With this commit, you should not have build problems.

**Comment by Shifuddin** [comment]
Hi @pfent ,
Sorry for late, was busy with reporting. What I have done just cloned my branch "https://github.com/Shifuddin/TumCampusApp" and performed git checkout resulting "Your branch is up-to-date with 'origin/master'."

Then again git rebase master resulting "Current branch master is up to date.".

Then again git merger origin/master resulting "Already up-to-date"

But facing same problem. Could not build the project. Is there any other way ?

**Comment by kordianbruck** [comment]
Bugs probably won't be fixed, and solution does not really show the technical merit needed to merge. Closing for now.

**Pull request closed without merging**
