### PR TITLE
Add checkstyle configuration based on google code style

### LINKED ISSUE #567: Add CheckStyle
We want to enforce a uniform code style. Jenkins job should include the CheckStyle Plugin

https://wiki.jenkins-ci.org/display/JENKINS/Checkstyle+Plugin

### PR DESCRIPTION
**Pull request by psukys**
## Issue

This fixes the following issue(s):
fixes #567 

## Screenshot

https://server4.wdkk.de/job/TCA-Android/460/analysisResult/

## Why this is useful for all students

Consistent coding style reduces maintenance costs.

### CODE REVIEW

**Comment by psukys** [comment]
I think it's dependant on #724 . Will continue on this PR after I resolved aforementioned one.

**Comment by psukys** [comment]
guhh, the *works on my machine*..

**Comment by kordianbruck** [comment]
@psukys work on jenkins, you just need to correctly setup the results file :+1:

**Comment by psukys** [comment]
@kordianbruck as far as I understand, jenkins doesn't do any processing, only parsing (took some time to realize this). And yet again gradle offers a plugin for checkstyle, but so scarce documentation for setting it up to the point where the plugin doesn't generate checkstyle tasks and I don't know where to go to resolve this, I'll try to deal so more this evening

**Comment by psukys** [comment]
@kordianbruck I think current checkstyle solution is sort of working, just that there are several things:
1. If there are issues from `checkstyle`, i.e. some style violations, the task fails -> build responds as fail
2. All of the `checkstyle` violations are shown (loads), thus there's most likely a subsequent PR that fixes all of these violations :D
3. The google checkstyle configuration fails without much information (just saying that Checker fails), but looking through related problems, I've only found configurations that *don't fail*.  One that I currently commited into is [okhttp checkstyle](https://android.googlesource.com/platform/external/okhttp/+/jb-mr1-dev/checkstyle.xml)

**Comment by psukys** [comment]
@kordianbruck , @pfent , should be ready for review. To review types of stylecheck violations, it's probably easiest to go for the [Type tab](https://server4.wdkk.de/job/TCA-Android/460/analysisResult/new/)

**Comment by pfent** [comment]
I think something like 140 should be appropriate, at last that's what I configured in our Project AndroidStudio codestylesettings:
https://github.com/TCA-Team/TumCampusApp/blob/master/.idea/codeStyleSettings.xml#L33

**Comment by kordianbruck** [comment]
>  thus there's most likely a subsequent PR

awaiting to see it :heart: 
Great work! This will hopefully be useful for future development.

**Comment by psukys** [comment]
@kordianbruck @pfent updated the config, is there something else that could be improved?

**Comment by kordianbruck** [comment]
@psukys I think we will adapt the config as we go. Next step is to get the comment bot report any violations of style, pmd or lint in github, so we can start fixing those things!

**Pull request merged**
