### PR TITLE
Use vector images instead of PNGs for Icons

### PR DESCRIPTION
**Pull request by pfent**
Since Android Studio 1.5 and the Android Gradle plugin 1.5.0 came out recently, we can now use vector images instead of bitmaps for the Icons used.

I mostly used the [Material Icons](https://www.google.com/design/icons/) as an almost 100% drop in replacement of the currently used Icons.

This significantly improves the sharpness of the icons for High-DPI devices

### CODE REVIEW

**Comment by pfent** [comment]
@kordianbruck can you maybe take a look, if any Icons are misplaced?

**Comment by kordianbruck** [comment]
```
java.lang.IllegalArgumentException: Invalid notification (no valid small icon): Notification(pri=0 contentView=de.tum.in.tumcampus/0x1090085 vibrate=null sound=null defaults=0x0 flags=0x10 color=0x00000000 groupKey=GROUP_8 vis=PRIVATE)
                                                                    at android.app.NotificationManager.notify(NotificationManager.java:222)
                                                                    at android.support.v4.app.NotificationManagerCompatEclair.postNotification(NotificationManagerCompatEclair.java:30)
                                                                    at android.support.v4.app.NotificationManagerCompat$ImplEclair.postNotification(NotificationManagerCompat.java:152)
                                                                    at android.support.v4.app.NotificationManagerCompat.notify(NotificationManagerCompat.java:225)
                                                                    at android.support.v4.app.NotificationManagerCompat.notify(NotificationManagerCompat.java:209)
                                                                    at de.tum.in.tumcampus.cards.Card.notifyUser(Card.java:233)
                                                                    at de.tum.in.tumcampus.cards.Card.apply(Card.java:177)
                                                                    at de.tum.in.tumcampus.models.managers.TransportManager.onRequestCard(TransportManager.java:281)
                                                                    at de.tum.in.tumcampus.models.managers.CardManager.update(CardManager.java:128)
                                                                    at de.tum.in.tumcampus.services.DownloadService.download(DownloadService.java:190)
                                                                    at de.tum.in.tumcampus.services.DownloadService.access$000(DownloadService.java:34)
                                                                    at de.tum.in.tumcampus.services.DownloadService$1.run(DownloadService.java:85)
                                                                    at java.lang.Thread.run(Thread.java:818)
```

**Comment by pfent** [comment]
This exception is also present in the current release of the TCA. The following code suggests that this is intentional?
``` Java
// Apply trick to hide card on phone if it the notification
// should only be present on the watch
if (mShowWear && !mShowPhone) {
    notificationBuilder.setGroup("GROUP_" + getTyp());
    notificationBuilder.setGroupSummary(false);
} else {
    notificationBuilder.setSmallIcon(R.drawable.tum_logo_notification);
}
```

The News feed icons are fetched from tumcabe and aren't affected by the client…

**Comment by kordianbruck** [comment]
Looks good now!

**Pull request merged**
