### PR TITLE
Add public transport favorites and highlighting

### PR DESCRIPTION
**Pull request by lnsp**
## Issue
This change adds user customizable highlighting of public transport lines. In the detailed view, you can tap the transport lines you want to track. It is a lightweight visual aid that is in my opinion more intuitive than selective filtering.
This fixes the following issue(s): #430 

## Screenshot
screenshot_1493809703
screenshot_1493809708
screenshot_1493809714

## Why this is useful for all students
The user can highlight his most used public transportation lines. This helps to track the latest departures he cares about.

### CODE REVIEW

**Comment by kordianbruck** [comment]
Can one of the admins verify this patch?

**Comment by kordianbruck** [comment]
ok to test

**Comment by kordianbruck** [comment]
Can we maybe have a info button in the toolbar to explain this? It would be hard to spot otherwise...

**Comment by lnsp** [comment]
Good idea, I will look into it.

**Comment by lnsp** [comment]
I added a help button in the toolbar explaining the general functionality. I am still looking into auto-refreshing the MVVCard in the MainActivity when the transport favorites are changed by the user. The same problem occurs when favoriting a dish in the cafeteria details view though.

## Screenshots
screenshot_1493815027
screenshot_1493815030

**Comment by lnsp** [comment]
A workaround would be to refresh the cards in the MainActivity when resuming to it. This would also fix the issue with the non-refreshing cafeteria cards.

**Comment by kordianbruck** [comment]
Probably a good idea. Lets do that in a separate PR.

**Pull request merged**
