### PR TITLE
Improve show ticket

### PR DESCRIPTION
**Pull request by Kailiangdong**
## Issue

This fixes the following issue(s):
Improve nearly all problem from issue #898 . Except showing ticket redemption status, not quite understand this. Have discussed with team-member.  Adding this means we should change our data model?

Except this, users can click the address then jump to google map, the text will then become red after clicking. 
Other change is showing on the screenshot.
## Screenshot

image

### CODE REVIEW

**Comment by saileru** [comment]
screenshot_20180625-153645

**Comment by saileru** [comment]
I made a few more adjustments: 
format price to e.g. "4,50 €"
added attribute for redemption state to the Ticket class

@Kailiangdong @schulzalexander @velev8 @kordianbruck What are your thoughts about the redemption state attribute in the Ticket class? I think it might be a good idea.

I am also open to suggestions about how to better display the redemption status in the UI.

**Comment by Kailiangdong** [comment]
@saileru  I will create a issue about that

**Comment by kordianbruck** [comment]
@saileru @Kailiangdong in the backend it is a datetime field - no? Are we not exporting this over the API?

**Pull request merged**
