### PR TITLE
Add code coverage

### LINKED ISSUE #568: Code Coverage
Now that we have unit tests, we should also be made aware how bad the situation is.

Lets have Jenkins also calculate the code coverage.

### PR DESCRIPTION
**Pull request by psukys**
## Issue

This fixes the following issue(s):
 - fixes #568 

## Screenshot
https://server4.wdkk.de/job/TCA-Android/426/jacoco/

## Why this is useful for all students
Having some heuristics to tell how well a codebase is maintained is beneficial in the long run

### CODE REVIEW

**Comment by psukys** [comment]
Finally got Jenkins talking with current configuration, just need to find a way to actually parse tests (because current coverage is 0 :laughing: )

**Comment by psukys** [comment]
Should be ready to review, @kordianbruck @pfent

**Comment by psukys** [comment]
In short, current problem:
1. Newer jacoco has problems in discovering tests in our current system,
2. Older jacoco doesn't have problems, but is extremely (like 4-5 years old) old,
3. Jenkins uses newer jacoco plugin (for parsing) and versions are non back-compatible
4. Maybe possible to downgrade Jenkins, but then it's a just a nuissance.

**Comment by psukys** [comment]
Thought: using alternative coverage tools? Jacoco has been for quite a while integrated as an official plugin into gradle, but if its acting up...

**Comment by psukys** [comment]
This looks extremely promising:
https://bitbucket.org/atlassian/clover

Comparison:
https://confluence.atlassian.com/clover/comparison-of-code-coverage-tools-681706101.html

**Comment by pfent** [comment]
IMHO getting a coverage percentage to display on the CI server just isn't worth the hazzle this seems to be.
Tests won't get better with that number, heck we're not even really trying to keep the lint warnings down :see_no_evil: 

Alas, if you want to have coverage numbers, just run it in AndroidStudio:
```
Run 'Tests in 'tumcampusapp'' with Coverage
```

**Comment by kordianbruck** [comment]
@psukys yea, I'm not sure that works with android either. Doing Roboelectric test cases is really a weird thing.

@pfent yea, this has eaten up enough time as it is.

**Pull request merged**
