### PR TITLE
workaround StickyListHeaders

### PR DESCRIPTION
**Pull request by jacqueline8711**
## Issue
This fixes the following issue(s): #719 

## Why this is useful for all students
Android O users can use Roomfinder again

### CODE REVIEW

**Comment by kordianbruck** [comment]
@pfent are we using this anywhere else? We have several of those autofills no? Isn't that the same things as the Suggestions?

**Comment by pfent** [comment]
@kordianbruck We're using StickyListHeaders in several Places:
* GradesActivity
* LecturesPersonalActivity
* RoomFinderActivity
* BarrierFreeContectActivity
* BarrierFreeMoreInfoActivity
* ChatRoomsActivity
* CurriculaActivity

**Comment by pfent** [comment]
The LecturesPersonalActivity is probably also affected by that crash, since there's a search bar in there.
@jacqueline8711 could you test this on your device?

**Comment by pfent** [comment]
Oh, and maybe setting this via XML should be a bit more neat:
https://developer.android.com/reference/android/view/View.html#attr_android:importantForAutofill

**Comment by jacqueline8711** [comment]
@pfent yeah, you're right, the same problem exists in the LecturesPersonalActivity

**Comment by kordianbruck** [comment]
@jacqueline8711 cool - please fix that as well then. Also add a comment to the issue in our repo and a `TODO` marker, so we don't forget to remove it once its resolved in the lib

**Pull request merged**
