### PR TITLE
Feature/russian_translation

### PR DESCRIPTION
**Pull request by aserhany**
With help of a native speaker

### CODE REVIEW

**Comment by kordianbruck** [comment]
@aserhany are you planing on finishing the translation?

**Comment by aserhany** [comment]
@kordianbruck : both translations are currently in this PR. However, I get lint errors on files I didn't change. Any tips?

**Comment by kordianbruck** [comment]
Did you merge the latest master?

**Comment by pfent** [comment]
[Travis complains about some missing closing br tags](https://build.wdkk.de/job/TumCampusApp/356/console)

Can you take a look at your "message_detail_text" elements, you can compare your raw text with the working version of the [english language files](https://github.com/TCA-Team/TumCampusApp/blob/master/app/src/main/res/values/strings.xml#L404)

**Comment by aserhany** [comment]
@kordianbruck @pfent : I merged the latest master and was able to resolve the conflicts.

**Comment by kordianbruck** [comment]
Thanks!

**Pull request merged**
