### PR TITLE
Remove quiz/survey

### LINKED ISSUE #603: Quiz: Remove or Improve
* Add explaination what it is.
* Fix it
* Or remove it

### PR DESCRIPTION
**Pull request by kordianbruck**
fixes #603

hope I didn't forget anything...

### CODE REVIEW

**Comment by pfent** [comment]
I recommend just grepping for "quiz" :smile_cat: 
I'll push some more removals

**Comment by kordianbruck** [comment]
I hope you didn't delete anything related to study cards right? Right?

**Comment by pfent** [comment]
Only did "Safe Delete" in Android Studio

**Comment by kordianbruck** [comment]
Alrighty!

**Pull request merged**
