### PR TITLE
Feature new room finder request

### LINKED ISSUE #255: Integrate TUM RoomFinder
The current version of the TUM RoomFinder is old and needs an update. 
The idea is to integrate certain features of that app into the TCA.

The published app "TUM RoomFinder" was removed from PlayStore on 02/19/2015. It's not working anyway anymore.

### PR DESCRIPTION
**Pull request by pfent**
I cherry-picked the commits from @thomasmauerer regarding the TUMRoomFinder from PR #292.
So this fixes #255.

Although I'm still getting error messages, but it seems the Server is still bugged. I'm getting a PHP error from https://tumcabe.in.tum.de/Api/roomfinder/room/search/00.08.055:
```
Parse error: syntax error, unexpected '[' in /var/www/portal/App/Modules/Api/Room.php on line 111
```

### CODE REVIEW

**Comment by thomasmauerer** [comment]
Hmm... When I'm trying it on the local server, it's working without any syntax error.

That's the response:
[
    {
        "room_id": "49764",
        "room_code": "5608.EG.055",
        "building_nr": "5608",
        "arch_id": "00.08.055@5608",
        "info": "00.08.055, Seminarraum",
        "address": "Boltzmannstr.    3(5608), Erdgeschoß",
        "purpose": "Seminarraum",
        "campus": "G",
        "name": "Math/Inf."
    }
]

**Comment by pfent** [comment]
The response looks good.
Probably @kordianbruck needs to update the server?

**Comment by kordianbruck** [comment]
I've fixed the server side for now. It contains many static functions unfortunately and some really weird magic like *callAlternativeVariant*. Also the model and controller in just one file. It will work for now, but there is definitely optimization required.

**Comment by kordianbruck** [comment]
Okey, some more issues arouse. The API is not too stable right now. For example the fetching of the default map is not working: https://tumcabe.in.tum.de/Api/roomfinder/room/defaultMap/00.08.053%405608

The Code is not really documented and somehow really complicated. I'll try to figure it out over the next couple days, but really its hard to work with this Spaghetti code.

**Pull request merged**
