### PR TITLE
Feature/new startup wizzard

### PR DESCRIPTION
**Pull request by kordianbruck**
We want to make the setup process more simple. For that we have implemented a way how to check the PK with TUMO from the TCA Server. 

This will remove one step from the setup process. 

@pfent I'm inclined to merge step 3&4 (Checkboxes) and simplifying it even more. What do you think?

### CODE REVIEW

**Comment by pfent** [comment]
Seems good to me. :+1: 
Everything simplifying the setup process is a step in the right direction.

We currently have 5 pages in the wizard, with your PR we are down to 4. However, we definetly don't need two consecutive pages of checkboxes. We can probably:

- [ ] Condense the 3 Chat checkboxes into 1. You currently can't enable the chat, if you don't accept the T&Cs, so that probably should only be one checkbox. Remove the "join new lecture chats" and give it a place in the settings?
- [ ] Combine the silence- and backgroundservice checkbox into one, since one without the other isn't really useful.
- [ ] Put the remaining 3 checkboxes on a page

**Comment by pfent** [comment]
Uhm, currently it's "Step 1", "Step 2", "Step **5**"
Testing on a fresh emulator, it also results in a:
```
retrofit.RetrofitError: 401 Unauthorized
    at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:388)
    at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
    at java.lang.reflect.Proxy.invoke(Proxy.java:813)
    at de.tum.in.tumcampusapp.models.$Proxy0.getMemberRooms(Unknown Source)
    at de.tum.in.tumcampusapp.models.TUMCabeClient.getMemberRooms(TUMCabeClient.java:170)
    at de.tum.in.tumcampusapp.activities.wizard.WizNavExtrasActivity.onLoadInBackground(WizNavExtrasActivity.java:122)
    at de.tum.in.tumcampusapp.activities.wizard.WizNavExtrasActivity.onLoadInBackground(WizNavExtrasActivity.java:30)
    at de.tum.in.tumcampusapp.activities.generic.ActivityForLoadingInBackground$1.doInBackground(ActivityForLoadingInBackground.java:64)
```

**Comment by kordianbruck** [comment]
Ai. I haven't finished the full workflow then, but now everything should be working just fine. 

Kinda tricky to implement this while not affecting previous versions.

**Comment by kordianbruck** [comment]
This fixes issue #302

**Pull request merged**
