### PR TITLE
calendar does not show past events

### PR DESCRIPTION
**Pull request by OliHalu**
## Issue
Past events were not shown in calendar. I set the number of past months shown in calendar to 2. Not sure if going much further into the past is necessary.

This fixes the following issue(s):
#574  - Calendar does not show past events
Fixes part of #682 

## Why this is useful for all students
Because now user can check past events in their calendar.

### CODE REVIEW

**Comment by kordianbruck** [comment]
@pfent actually this is troublesome. Really we should properpy do paging. So just load one month each time. Most users won't go into the past, so enabling all users to simply download two more months, puts a lot of stress on the TUMonline DB.

**Comment by pfent** [comment]
@kordianbruck how would paging work with a calendar, that is synced to the device calendar?
Also, what's more stress? My calendar is currently 36kb for the last 3 months, which does not seem to be very tasking to me...

**Comment by kordianbruck** [comment]
No clue how those synchronized cals work. But thats not implemented right now in any case.

Its not the size that matters here. TUMonline is doing like 10 union alls on different tables that have several million records. This times 20k devices that sync this at least every week, is quite much. Already the calendar API is the one using the most CPU time. 

@xsrf you wouldn't happen to have any statistics about this?

**Comment by pfent** [comment]
Hrrngh :man_facepalming: 

We haven't released those changes, yet, So there's no rush fixing that.

I suppose we could do something more clever than a [`DELETE FROM calendar`](https://github.com/TCA-Team/TumCampusApp/blob/ad28cb21894c58d899cd8186171fe09b78c7462a/app/src/main/java/de/tum/in/tumcampusapp/component/tumui/calendar/CalendarController.java#L197), every time we sync it :man_shrugging: 
However, we potentially show wrong information for the past then (e.g. Sync Monday, event gets canceled on Tuesday, Sync Wednesday: we can't possibly know when only syncing future events). My reasoning was: Just trust TUMonline...

**Comment by xsrf** [comment]
Access to "kalender" isn't a problem at the moment (I guess). The API gets called twice a week per token on average. Only few devices call it ~20 times per week. Requests are processed within 1s or less.

**Comment by kordianbruck** [comment]
@xsrf cool beans - so this means we can move ahead with simply adding some months to the result set.

**Pull request merged**
