### PR TITLE
correctly checking api (eduroam)

### PR DESCRIPTION
**Pull request by jacqueline8711**
## Issue
I think this should fix both #702 and #698 but I haven't tested it yet

### CODE REVIEW

**Comment by kordianbruck** [comment]
Work in progress then till tested :+1:

**Comment by pfent** [comment]
@jacqueline8711 Could you already test this?

**Comment by jacqueline8711** [comment]
@pfent to be honest I don't have an old enough test device I think testing in an emulator is not possible because it doesn't have wifi. Ideas?

**Comment by pfent** [comment]
Then let's merge it anyway, maybe @M-FF-M can test it proper

**Comment by jacqueline8711** [comment]
I should work fine. I know what caused the crashes,  i.e. what I did wrong and I fixed that

**Pull request merged**
