### PR TITLE
Remove EnhancedSearchRecentSuggestionsProvider

### PR DESCRIPTION
**Pull request by psukys**
## Issue

Use Android builtin solution instead of `EnhancedSearchRecentSuggestionsProvider` 

## Screenshot

Not applicable

## Why this is useful for all students

Less code is probably better.

### CODE REVIEW

**Comment by psukys** [comment]
I'll do some manual usability tests and maybe could write a test or two if applicable.

**Comment by psukys** [comment]
Alright, it seems that recent search suggestions are not individual per activity, whereas previously they were. Was this the original intention with Enhanced[...], @pfent ? The documentation is pretty vague on this class.

**Comment by pfent** [comment]
If that's the only difference, that's totally fine with me.

I'll take a closer look tomorrow

**Comment by kordianbruck** [comment]
@psukys yes, the id parameter usually distinguished the different search values: 
```
* @param id        String identifying the SuggestionProvider. Must not contain blanks or any
-     *                  other special characters
```

**Comment by kordianbruck** [comment]
I think we want to go towards a unified search activity in any case, so this is fine for any casse.

**Comment by pfent** [comment]
> +16 −343

Much less complexity for basically the same functionality :tada:

**Pull request merged**
